apiVersion: v1
description: Airflow running with KubernetesExecutor, git-sync and logs to s3
name: airflow-kube-s3
version: 0.0.3-alpha+003
appVersion: 1.10.9
icon: https://usr/local/airflow.apache.org/_images/pin_large.png
home: https://usr/local/airflow.apache.org/
sources:
  - https://usr/local/airflow.apache.org/
keywords:
  - workflow
  - airflow
  - dag
  - aws
  - git-sync
